config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'pages#index'
    get 'cv', to:'pages#cv_section'

    get 'golf', to:'golf_scores#index'
    get 'new_golf_score', to:'golf_scores#new'
    get 'edit_golf_score', to:'golf_scores#edit'
    post 'new_golf_score', to:'golf_scores#create'

    get 'golf_location', to:'golf_locations#show'
    get 'new_golf_location', to:'golf_locations#new'

    get 'diving', to:'dives#index'

    get 'info', to:'pages#info_section'

    post 'golf_scores', to: 'controller#golf_scores'

    resources :golf_locations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_and_belongs_to_many :dives
end

app/models/dive.rb
class Dive < ApplicationRecord
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :countries
  has_and_belongs_to_many :dive_leaders

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :start_pressure, presence: true
  validates :end_pressure, presence: true
  validates :max_depth, presence: true
  validates :locations, presence: true, length: {maximum: 50}
  validates :countries, presence: true, length: {maximum: 50}
  validates :dive_leaders, presence: true, length: {maximum: 50}
end

app/models/dive_leader.rb
class DiveLeader < ApplicationRecord
  has_and_belongs_to_many :dives
end

app/models/location.rb
class Location < ApplicationRecord
  has_and_belongs_to_many :dives
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController
  def index
    @dives = Dive.all
  end

  def show
    @dive = Dive.find(params[:id])
  end

  def new
    @dive = Dive.new
  end

  def create
    @dive = Dive.new(dive_params)

    if @dive.save
      redirect_to @dive
    else
      render :new
    end
  end

  def edit
    @dive = Dive.find(params[:id])
  end

  def update
    @dive = Dive.find(params[:id])

    if @dive.update(dive_params)
      redirect_to @dive
    else
      render :edit
    end
  end

  def destroy
    @dive = Dive.find(params[:id])
    @dive.destroy

    redirect_to diving_path
  end

  private

  def dive_params
    params.require(:dive).permit(:name, :short_name, :organization, :web_page, :words, licence_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dives_helper.rb
module DivesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dives/_form.html.erb
<%= form_with model: @corpu do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="option">
        <%= form.label :name, class: 'option_title' %><br>
        <%= form.text_field :name %>
        <% @corpu.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <%= form.submit({class: 'btn button'}) %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to t('.home'), root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('.cv'), cv_path(anchor: 'cv_info'), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('.diving'), diving_path(anchor: 'diving_info'), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('.golf'), golf_path(anchor: 'golf_info'), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('.info'), info_path(anchor: 'info'), class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item <%= 'active' if I18n.locale == :es %>">
          <%= link_to 'ES', root_path(locale: 'es'), class: 'nav-link language lang_es' %>
        </li>
        <li class="nav-item <%= 'active' if I18n.locale == :gl %>">
          <%= link_to 'GL', root_path(locale: 'gl'), class: 'nav-link language lang_gl' %>
        </li>
        <li class="nav-item <%= 'active' if I18n.locale == :en %>">
          <%= link_to 'EN', root_path(locale: 'en'), class: 'nav-link language lang_en' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="eng">
  <head>
    <title>PersonalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8a2b01bd35.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main id="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/cv_section.html.erb
<div class="container cv_section">
  <h2 class="cv_sec_title"><%= t('.cv_sec_title') %></h2>
</div>
<div class="container">
  <%= link_to 'Download', class: 'btn fas fa-2x fa-download"' %>
</div>

app/views/pages/diving_section.html.erb
<p>halo</p>

app/views/pages/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_pack_tag 'index' %>
<% end %>
<header>
  <div class="container">
    <%= image_pack_tag 'header_image.jpg', id: 'background_header' %>
  </div>
</header>
<section class="cv_info">
  <div class="container cv_info_main divider">
    <div class="row">
      <div class="col-md-8">
        <h3 class="section_title"><%= t('.cv_title') %></h3>
        <p class="section_text"><%= t('.cv_text') %></p>
        <%= link_to "CV area", cv_path, class: 'btn btn-secondary section_btn' %>
      </div>
      <div class="col-md-4">
        <%= image_pack_tag 'cvsection_image.jpg', class: 'section_image' %>
      </div>
    </div>
  </div>
</section>
<section class="diving_info">
  <div class="container diving_info_main divider">
    <div class="row main_section">
      <div class="col-md-4">

      </div>
      <div class="col-md-8">
        <h3 class="section_title"><%= t('.diving_title') %></h3>
        <p class="section_text"><%= t('.diving_text') %></p>
        <%= link_to "Diving section", diving_path, class: 'btn btn-secondary section_btn' %>
      </div>
    </div>
  </div>
</section>
<section class="golf_info">
  <div class="container golf_info_main divider">
    <div class="row">
      <div class="col-md-8">
        <h3 class="section_title"><%= t('.golf_title') %></h3>
        <p class="section_text"><%= t('.golf_text') %></p>
        <%= link_to "Golf section", golf_path, class: 'btn btn-secondary section_btn' %>
      </div>
      <div class="col-md-4">
        <%= image_pack_tag 'golfsection_image.jpg', class: 'section_image' %>
      </div>
    </div>
  </div>
</section>
<section class="info">
  <div class="container info_main divider">
    <div class="row">
      <div class="col-md-4">
        <%= image_pack_tag 'infosection_image.jpg', class: 'section_image' %>
      </div>
      <div class="col-md-8">
        <h3 class="section_title"><%= t('.info_title') %></h3>
        <p class="section_text"><%= t('.info_text') %></p>
        <%= link_to "Info section", info_path, class: 'btn btn-secondary section_btn' %>
      </div>
    </div>
  </div>
</section>
<section class="info">
  <div class="container info_main divider">
    <h3 class="section_title">Contact</h3>
    <div class="product_form">
      <%= form_with local: true do |form| %>
        <div class="form-group">
          <label class="required" for="name"><b>Nombre Completo</b></label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Juan Martinez Fernandez" required>
        </div>
        <div class="form-group">
          <label class="required" for="email"><b>Email</b></label>
          <input type="email" class="form-control" id="email" name="email" placeholder="nombre@email.com" required>
        </div>
        <div class="form-group">
          <label class="required" for="subject"><b>Asusnto</b></label>
          <input type="text" class="form-control" id="subject" name="subject" placeholder="" required>
          <div class="invalid-tooltip">
            Por favor introduzca un asunto.
          </div>
        </div>
        <div class="form-group">
          <label class="required" for="content"><b>Contendo de Email</b></label>
          <textarea class="form-control" id="_email_content" rows="4" required></textarea>
          <div class="invalid-tooltip">
            Por favor introduzca el contenido del email.
          </div>
        </div>
        <button type="submit" class="btn btn-secondary">Submit</button>
      <% end %>
    </div>
  </div>
</section>
<footer id="footer">
  <div class="container">
    <%= link_to '', 'https://www.facebook.com/brais.calvinoravina', class: 'fab fa-2x fa-facebook-square footer_link', target: '_blank' %>
    <%= link_to 'https://www.instagram.com/photobrais/', class: 'footer_link', target: '_blank' do %>
      <%= image_pack_tag 'instagram_logo.png', class: 'footer_logo' %>
    <% end %>
    <%= link_to '', '', class: 'fab fa-2x fa-linkedin footer_link', target: '_blank' %>
    <%= link_to '', '', class: 'fab fa-2x fa-github-square' %>
  </div>
</footer>

app/views/pages/info_section.html.erb
<p>halo</p>